-- BhuGyan schema — Pipeline 1: Places (the spine)
-- ~800+ place nodes with geometry, hierarchy, Hindi names + graph edges.

CREATE TABLE IF NOT EXISTS places (
    id          BIGSERIAL PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,            -- stable key e.g. "maharashtra"
    name        TEXT NOT NULL,                   -- English display name
    name_hi     TEXT,                            -- Hindi name (Wikidata enrich)
    place_type  TEXT NOT NULL,                   -- country|state|district|city|river|lake
    parent_id   BIGINT REFERENCES places(id) ON DELETE SET NULL,  -- hierarchy
    geom        geometry(Geometry, 4326),        -- polygon/line/point, WGS84
    centroid    geometry(Point, 4326),
    properties  JSONB NOT NULL DEFAULT '{}',     -- source attrs (iso codes, etc.)
    source      TEXT,                            -- natural_earth|osm|census|wikidata
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Graph edges between places: borders, flows_to, etc. (generated by PostGIS).
CREATE TABLE IF NOT EXISTS place_edges (
    id              BIGSERIAL PRIMARY KEY,
    source_place_id BIGINT NOT NULL REFERENCES places(id) ON DELETE CASCADE,
    target_place_id BIGINT NOT NULL REFERENCES places(id) ON DELETE CASCADE,
    edge_type       TEXT NOT NULL,               -- borders|flows_to|contains
    properties      JSONB NOT NULL DEFAULT '{}',
    UNIQUE (source_place_id, target_place_id, edge_type)
);
